name: golo
description: A Dart package for the logic of Go/Igo/Weiqi/Baduk board games.
version: 0.0.1
homepage: https://github.com/ReiRev/dart_golo
repository: https://github.com/ReiRev/dart_golo
funding:
  - https://github.com/sponsors/ReiRev
  - https://ko-fi.com/ReiRev

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  collection: ^1.19.1
  lints: ^4.0.0
  test: ^1.24.0
